### ISSUE TITLE
api key solution

### ISSUE THREAD

**Issue by vinitparekh17** [ruchik02/weather-app-using-js-api#2]
glad to know that you secured your api key but you uploaded your project on netlify but it is not gonna work anymore so it will be meaningless so you should replace that place with " process.env.api_key " and add your api key in netlify environment as i mentioned img above , also i would like to know that from where do you learning , as i'm also passionate under graduate web developer , you can check my repo

![Screenshot (58)](https://user-images.githubusercontent.com/77158947/161398122-aae22577-58a0-48a7-bd49-d20a5714e7c9.png)

**Comment by ruchik02** [comment]
Thank you for giving the solution, but where I used  process.env.api_key

**Comment by vinitparekh17** [comment]
process.env.api_key should go in the same line of your app.js and that
value should go in netlify environment I attached the screenshot in issue,
also I'm genuinely passionate about web development as much as you do
https://www.vinitparekh.rocks
here is my portfolio https://gitHub.com/vinitparekh17 you can also check my
work which I built in last 7 months. I would like to ask you that from
where do you learning this ? And I believe that sharing our knowledge will
be more beneficial for us so can I be your professional friend to discuss
tach stuff and doubts with each other if you don't mind 😊

**Comment by ruchik02** [comment]
Ok, but  if I use  process.env.api_key  then process is not defined its error in my console I'm really thankful to you but again I didn't get your point 
can u give me the prop solution so that I can secure my API 
const weatherApi={
    key: process.env.api_key ,
    baseUrl:"https://api.openweathermap.org/data/2.5/weather"
}
well I learned from Google, YouTube, and also I buy  a coding ninja web development course. i buy different course from different -different site like Udemy, coding ninja, coding block.

**Comment by vinitparekh17** [comment]
Sorry to say that but I forgot to notice that your entire website is frontend work so process.env method is not gonna work because that value will be stored in server side which can't be accessed with frontend even if you manage to hide your key then anyone can see by inspecting in browser,  weather api is open sourced so no worries no one can miss use with it so chill 😅👍🏼👍🏼.

I had bought Udemy course from Angela Yu and React course from Learn code online , Can you help me to improve my skills? If yes then from which social platform should I contact you?

**Comment by ruchik02** [comment]
That's why I think how to use procress.env.key because it is used in node.
Sure why not 
if u have any prob in web, I'm ready to help you.
You can contact through mail, this is my mail id sruchika004@gmail.com 
just message me

**Comment by vinitparekh17** [comment]
Yes sure 😊
